name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ba323479b490e714f456716cdabf6380f57344fbbf70fa5d4c12b785fb4afc1"

[versions]
fabric = "0.15.3"
minecraft = "1.20.2"
