name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec3d9eb82225fffaeb5b484e13c94d9cc584ce0ca9ab4c8a437282fd066a031a"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
