name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be16f862e466c64493da136208b75302270f0b216c30eaa1e0b71eea6667ecd4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.2"
