name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "851479ec1088f81ef665de2ff353b514a2d1ce95bb689f1a9352998b86be7c71"

[versions]
fabric = "0.14.25"
minecraft = "1.20.2"
