name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5edf706068518946752c715b4b9b15673fc9a7856645f9104d315651b828fb91"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
