name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63a2c5d82fd2e1f1f54f6d5d2c6b22db1464a58ff716a5a85b845b0ec1e3c9fa"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
