name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30ee19d8d1d300ed0420b53c82aa0ce31d138a623399edefd05d5d1d10157a72"

[versions]
fabric = "0.15.3"
minecraft = "1.20.2"
