name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62eb2ee4d8ace6ae765c4a08bdbd260f573bc74e1df0222be712455a208274ac"

[versions]
minecraft = "1.20.1"
quilt = "0.21.1"
