name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b907300fc5471661bcb09d669e8e27bdb86563d9a4ee763cb614d4882ba786a"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
