name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fadd152472b17cdfd286dc17717aaedc7456f4c265fedbad56e9dafcc6019f5f"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
