name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-wynn-1.5.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e32f329f8aea5ed0784a357c1b65fea452a53e8e656cfdd02f9f570cad9db109"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
