name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c71449c3137ecdc17e4fe6fa89afe7c2dd70b9837dea569da32aa5ffedbd6ea"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
