name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.0.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baffa048362967987410676420e88f5b382ed3fa5225263531f27456e311f4a1"

[versions]
minecraft = "1.20.1"
quilt = "0.19.5"
