name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.5.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7695b5236a2c41f456205b744e0f624251c343e6a8e8825b5efb048fa19f603e"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
