name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6a79b1a0e334d53403ec7bf113a86a5ca27a1f99200c700ca18b6521e120d60"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
