name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "544bf41c8742b8bf15693ee6209c0bf6c631bdbd2f733fbc9366338f3a10da2d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
