name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76e0c448d125933139cf8a81c8f4068b124e46a02877ef43b5c631ebafc7f704"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
