name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.2.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c9adfd7402fed80887cab075e9c7e28590c74466e7e5cd4e09f0fd73be14520"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
