name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-quilt+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d731a7e0d70292601543ce5d2d013c6cbcaea04d32ab79ed84a36cdd4f9693a"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
