name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ec310885caa56f767fe62a2477e128cacdacf6ffc64365193949cfe8d24d418"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
