name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "289987d49b7ff4127425e2a3c091e028fb972aee54672a0495a977905d7e3d1b"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
