name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0509ea14279747e6f640a4d98ba93d1fbd445712d560dfa5cf39d67524d2ed9f"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
