name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba977c0d4d5608e86b580c4a32c6913c100c884ea6e776936122f15d3e9f8709"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
