name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b637b6b34e6093ccb01209b232a004180b3f22dd5f216e4391542d60b4b798d2"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
