name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "726408df3f3f076ff22eacd0690fe2fc57fca8bc19241d926ab288a730eb8856"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
