name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bd71505cb085156c333b541057eb81a56caed8dba0edf4d36b0e38a886ee22e"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
