name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a0778415b5ff55faf5b3664c8a33309a38ecd29d7b097e2269a314a2011883c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
