name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3628f2f14656c3f6878b6e06ce8a98169cb9fd1033e37d6c1aa55f456572d10f"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
