name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27973adef4bc38da198023e54443b64d1ee33df172e21c427732eb8d53cae21a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
