name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41d05ed8c205ba8e02f8f65b72fd38b31125d87727c0e3be90e19b49b8b05af9"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
