name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e258778d1fee5012a067296f66a4e13899058361648d90f83297e6da622d7db"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
