name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "582c13733830a1fbca5416f57929238c25eb657ad47f50e0429650dacac3fbee"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
