name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ef680aec3468a7491a52838ce79869b9e3391c1364a84f0ad2bb2cca7a08768"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
