name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-neoforge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d69f76722eb9a29841a66b6afb7b9b8b31919893419c5b40815ed3ca66f2ecbd"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
