name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c0395f1e8fdd1e99e90ba2b6153d633501d7b35068fb72023c76e04a7a7b8df"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
