name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79dc864bd53292cc8b9bd79912b5e09f9a9eb9eea564c57d3fc982f11f156ade"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
