name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf5ce94ba40da286ed1b5cd2e8237a014be24e5200544d8eb93cc5012cb3860c"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
