name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99c1491ae3f0804c7a743a76f2c11b60f3c506c2c5c295cdd2b47ecb302d7ef5"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
