name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9ec93c1fa67123b9b37edbbcf2bc24203fcab03e7ff20e339e90bff1b035af4"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
