name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c6fe2b2f50e81f893cb0c1d21fb93f4d7453b67b4974747ec06dac7957b024b"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
