name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82377b29e33d44eaf3b15e36f330b5f3a0ea4698a6d5f7f81cac9f8533d97121"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
