name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50969d0dfbcb8eb7314af436ec3856a64c1f25c9ef59ad9c6cb7659b6776c30a"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
