name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64e8a3901b9d7e58000643841f0f44d48682ccc210119fbf05228c208f809c63"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
