name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a69adc8cedb325ce3f7ef9c8c00371446cc74f7c4e8d328a967f6162043f2075"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
