name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11ab62a4141bbbbc9251c0ede54e40b2df315a32e16c55b797d245067349a9ee"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
