name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b167de705f6b2953749b2c45cbec5181fd4c7a8838d42c7a159ccd40f8b5427b"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
