name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "905af19fc35c7f176ffd6a239fa62bf0b6d583d231bd1371d3bf16881b4639a6"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
