name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10a7f9fb975c4f8dc294e609eb3d086320ed527600bf9ebd34b28c8f931a2f46"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
