name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.0.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "796d43776236df8afc0d980d3628da3f6f4631e91fa3fd4c7fa1b41209028d0f"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
