name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.2.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "802fa6e144d58ab311578adbebea35a093dedf88f472a9f7dc12f93958af833b"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
