name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.5.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03c5a539312babdc2725c93286cf2c53bf3a0b82095b98031779257abf5c6a7f"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
