name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "495c3f5037b0c2ed1ef5237bcaac5bc8b57f1ce0ce34d3f01411c9d32bfe291a"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
