name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d19c71a2d1eb15f3c2346e80f74f318f6e77c0d74577f2d172eb98e1c4e2dd79"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
