name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b18d83c59e0bd8383d91eb2ddc09616c48e5971842f4793e16afd86e65240bb"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
