name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df698af2eced9cd74734a0c30ef9dfa90321bad1982c4e6a9024343ad178e5de"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
