name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.5.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c422a83f4a5c01fe34dbc1499ff1a7182dcb91807f9f2fdc096b49ebceec64d6"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
