name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d313a05de1fd8e8ae0ab33c762a0411686f466373b847132722a4de726c8fc33"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
