name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "facdde363c8711ab8ec7ba655796ccbe589e15006f28b039e1c97406b3f3e546"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
