name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32d17d19dc049829ae150310334a2da419a59e9e05576685c9506945df8f9bae"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
