name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c49e80f74025778795ffde5d179f935bf26ee4c575a2281e40d1a2eb6ce2263"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
