name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca5ab8f54e37bede605439ca5dc8f66501ed41cc869d050f0f971405e8c7c662"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
