name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-forge+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b07527d79c5b42eeff4815ec86c9d674ae7137647821ee4857c004ae20ca48f1"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
