name = "Fabric 1.20.1"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "879ad70f974c8cecba84d3d33cd8202af190892f76473a43103619c3ff3f5867"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
