name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-fabric+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94ecbe600b88cee83f9efca8cd721bbcc5bdaa981abfc88308472705df595f38"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
