name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.2.0-fabric+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7000f8095b89f2616730fd053a333f3ed1f6e1e84c4a39d17fc8ecd17fd25c78"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
