name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-wynn-1.4.0-fabric+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49bc94ccbfe24b19b2b2afe90f4d93c981ae492e61fba364d4217835f2068bc7"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
