name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.0.0-fabric+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40c479909a91dc6afa94dbfb9bd679f7a119aad1f407821a857db6158e9c0a02"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
