name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cae6760fe33b5dfa110726c9acb287f9cb9c1c868e054b48227c12cb28836b8"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
