name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-wynn-1.5.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2509dd5ab5018ebd0a38d889c4cd23893141c4fbaea67f288d264e671b934bd6"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
