name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.5.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7ea5467dc515830d869008e73eba47fc6521954890c23e153cabe4f5f967dff"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
