name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-fabric+1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85c522bcc23ee23c25ab25e3956ac26974b045deff7cf9e1d34d635e25a43e12"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
