name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8660d6dd479b38811d874e6396ffb713fee2066c7b1fe856c22de9f0f3d5b95"

[versions]
fabric = "0.14.25"
minecraft = "1.20.2"
