name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b3387d4ba65eb7ee45613730387f09fa08f2136a831c5fe7fcaa05e15d8c46f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
