name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32200f4d6c7a0557f66307b482c397647b1aa9199d109a6014ecce3a37edb21f"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
