name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0bbcade24f9cef8a440477022dccfe500664415b274f9e3ed966831cd3fc763"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
