name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e60f406d4fa7905b053307bc4ef79acdf441ceab48d5754beb61e8acf9deac6"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
