name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d3b1656d27e6d4f19dfd7fb21310cb286753f3cb2ad55078aafe56fc6251824"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
