name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8683703b7598b701b3353f6cb1fbce50c1009176c94421418ddab87ffc164495"

[versions]
fabric = "0.15.6"
minecraft = "1.20.2"
