name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63166098f2538db62af055ac1664f099bbc8c5b1cac474335dd001948d5456a4"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
