name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7832d22c343a6416b917ca89b39cc08a4f26a2273b078f6024f01256951f196c"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
