name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e83c6610b2098e951f3d570522eef2cd8f3e93e049fc3bbf2fc1b2df057fcf0e"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
