name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfb94a28945ae91d27b54122d16f14e608dfb6365c5ed7b6fd1d037a4ce15f57"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
