name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7c5900773b1cdbece5b164cfa2e11ede52caf6b6caa94c38eba3841474c411c"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
