name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56bd55b9ddab691e5a473a2c7c4953a894412792b70869690728841f34c92bd2"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
