name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20a53b10b1d7ef7c52465302aa479ea91c0e2ea9ed6c165d88191349b8ddc671"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
