name = "Multiplicative testbed (DO NOT USE)"
author = "Menacing Person"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07336fe071e497ca9cff14db416dbd91d36f8abd766359fbda82ec5647b09b0a"

[versions]
fabric = "0.14.25"
minecraft = "1.20.2"
