name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-quilt+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c673267a10fa62e9ade897a1ed83254f5dad358cc217711cd0cea396ba9da532"

[versions]
minecraft = "1.19.4"
quilt = "0.20.2"
