name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-quilt+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17fb45e1dee9b7140d30de8213b91548e4080881acdaeec2a3d69f69a9cbceaf"

[versions]
minecraft = "1.19.4"
quilt = "0.20.2"
