name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c6a280b7321af3ae6698bf4b626c426e2db0f6e1fbff738b2fae47fb85c2b2c"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
