name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "887090c74d651c3f38c8c1e3e85c3fe27fb39dd8e04e408bbd7110cf41975fe2"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
