name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.7.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d27ce761baad61ee1271cd3116767f1f3d78bdd0fd153133b50bebc2b0a06a3"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
