name: Release pack

on: [ push ]

jobs:
  packup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Restore packwiz file cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/packwiz
          key: packwiz-cache-${{ github.run_id }}
          restore-keys: packwiz-cache
      - name: Restore golang dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build/
          key: go-dep-cache-${{ github.run_id }}
          restore-keys: go-dep-cache
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          cache: false
          check-latest: true
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Compile modpack
        run: ./scripts/test_commit.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: packs
          path: packs/
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "packs/*"
          body_path: ./conf/changelog.md
