name: Release pack

on: [ push ]

jobs:
  packup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          cache: false
          check-latest: true
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip dependencies
        run: pip install tomli tomli-w
      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Compile modpack 1.19.4
        run: script -eq -c './setup.py 1.19.4' /dev/null
      - name: Compile modpack 1.20
        run: script -eq -c './setup.py 1.20' /dev/null
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: packs
          path: packs/
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "packs/*"
          body_path: changelog.md
