name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce95b57c7695d86ff1814285d2f33066c9402c3b1786fad236c2fd3cf88081ff"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
