name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.2.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbaac3e528145884acc9277e39906ea11626466d4b760c676baf43de94beb753"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
