name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "634711d1c8d7dbadadba2f05074b88e28ccd3b5707e98e60f6a966121f13d8d0"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
