name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-wynn-1.5.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbfedaf52f4b1e92d24dc2cf26073d7662a0dec71e04e9a08c79f6c1356e9ef0"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
