name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.2.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5da5f5c2a5405deeea428f79dbe57945ccd28dc51a68f592e109bac0d6b7330e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
