name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffe8c2503972c107a7c6ccf7394f3c9413e5721fdfad871c0ecde08e5250b957"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
