name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.6.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b735af15d04906f9fc3797637093abbb08197435d310e528ffe66e54fb0e922e"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
