name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.2.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e954c88290cfcb28664ffecb290155d9f48f15f9002756e146cd620ed0f20322"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
