name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.3.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47995eff37c4639f71f23a23f39474bbb0eaa796f6629b5414934e00809afd58"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
