name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.4.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52d61999bb91ff02585e481124a9cbca95e90ae2d77759f54b9ee90cc682e0ca"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
