name = "Multiplicative"
author = "Menacing Person"
version = "Multiplicative-3.0.0-fabric+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ef78aac79badc9aabb5845a0f8692770dc83b335be3357f3f9296ac47e8d7b9"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
